version: "2"
services:
  dimepi:
    build: .
    network_mode: "host"
    privileged: true
  sonos-api:
    image: chrisns/docker-node-sonos-http-api
    ports:
      - "5005:5005"
    network_mode: "host"